### ISSUE TITLE
Update lookup content, media, flashcard service

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/course_service#25]
## Parent
[course_service20](https://github.com/orgs/IT-REX-Platform/projects/1/views/1?pane=issue&itemId=30368789)

## Description
Whenever some resource in the services is created/deleted, the lookup is updated.

## Acceptance Criteria

- [x] lookup gets updated when changes in the content service occur
- [x] lookup gets updated when changes in the media service occur
- [ ] lookup gets updated when changes in the flashcard service occur

**Comment by BlueWaves2** [comment]
After starting implementation, I've realised it would make more sense to create two different topics, due to different levels of information available between services.  While content always has a reference to a chapter, e.g. Media only has a reference to a Content ID. Therefore, the corresponding chapter/course for a Media needs to be resolved. By having the update information go through the content service first, we can replace the content ID with a chapter ID and then forward the message to the course service.

# Proposed Service Topics

## Topic: Resource Association
### Involved Services:
publishers: 
- contention service

subscribers:
- Course service

### Message Content:
- ChapterId, ResourceID (Entity ID), CRUD Operation

## Topic: Resource changes
### Involved Services:
publishers: 
- media service
- flashcard service

subscribers:
- Content service

### Message Content:
- Entity ID, List::ContentID, CRUD Operation
