### ISSUE TITLE
Backend add semester to a course

### ISSUE THREAD

**Issue by LG1401** [IT-REX-Platform/course_service#39]
## Description
Add in which semester a course takes place.

## Acceptance Criteria
- [ ] courses have a semester

**Comment by PaulBredl** [comment]
@SkyDiverStar should this just be a string? Or how should this field look like?

**Comment by SkyDiverStar** [comment]
String would be probably the simpler solution. Don't know if Dates would be easier, but guess not. @PaulBredl

**Comment by myluki2000** [comment]
1. Using dates I don't see the point of, because then what's the difference between that date and the "startDate" we already have?
2. An object that consists of an enum for SummerSemester / Wintersemester and a number storing the year would be elegant, but wouldn't work for other organizational structures (e.h. trimesters)
3. Strings would be easiest and most flexible
4. But if we use completely free-form strings anyways, why not just write the semester into the title of the course?

For what exactly is the semester information needed again so that we need it in a seperate field? I can't remember

**Comment by SkyDiverStar** [comment]
So we can sort the courses according to their semester. It was UX related topic, so that you can see which course is offered in the winter and which in the summer. 
One step further would be not only "WS/SS" but "WS 23/24" and "SS 23".

**Comment by PaulBredl** [comment]
I wouldn't use an enum, because like Lukas said, then other organizational structures don't work, but also strings are bad, because then every professor would probably start a different naming system like
- "WS 2023"
- "WS 23/24"
- "Wintersemester 2023/2024"
- "2023 Winter"
- ...
And sorting or filtering is a bit pointless

**Comment by myluki2000** [comment]
Why not sort by course startDate?

> So we can sort the courses according to their semester. It was UX related topic, so that you can see which course is offered in the winter and which in the summer. One step further would be not only "WS/SS" but "WS 23/24" and "SS 23".

**Comment by LG1401** [comment]
The goal is also to be able to just show the courses that are part of the current semester for example to show them in the "courses I'm attending" part of the navbar. I'm not sure if we can do this just by the start date of a course.
I first thought of an enum but I see your point about it being inflexible.
Maybe we can do it as a string and suggest the most common ones such as SS23 in the right format and offer an option "custom semester label" where the user also gets warned that this should only be chosen if no other label applies

**Comment by myluki2000** [comment]
We could make it so the admin of the learning platform can define date ranges that define a semester (or trimester) and then all courses with a start date within that date range are treated as "from this semester"

**Comment by PaulBredl** [comment]
We could have a tag system like in the content service. So you can "tag" a course with a string like semester. But that might be too much work for this feature
